language: node_js
node_js:
- lts/*
install:
- yarn install
script:
- yarn build
deploy:
  provider: surge
  login: allenclark@u.boisestate.edu
  domain: cruel-leg.surge.sh
  token: ZHw6Qhtmlf0+s8Q8ajq1fPlRSQ7mtRgDaIq35Miav/Q/O2+FwEJKQ2qtaS0RhDiUXCELm0Qx3y2WjNz9zJKVleCKY7lM+KNqIRHg7B18t/MkoYU9V7vaEq2EaoF08KEHmyXbUg8vbNGmRGAoZOT9dUZnmt+HUOlVFf8Ae/PqJ8gdLFdiPCmzkxqwla7NIoyHz7SCFHeRLkK/yzSuAWZo2JxNPyhdfEFkW0FysSeCIAVqzD3fCwKVCjCI+6RqKsI0vWsNdxH/rsVljE6D4qpcvD4r1tr+VpJYym68LWnh29PsGh5bmpOh6tltXwZw2W0nAYzqiCEfWexgOImyp6suhs+UFoLaFr5ocjaEy4h8LG8R+x1np0D0Kgufx2xz/fXCnENf3BGoeqCRwuwL6aZhhe1ga1P6H+YpmkBxbdhY9irv2glmI/zuOkxziXyZsjFM+8hWYlbnLKU7DuFYo7Uk8holilKqnr4y8gxpX6wh1TJqgzGs+zVtWvHbONGkFXVLf0xc76tdR22FtclR1TqfohnSMMagB6mnLtgPlYd/vKlmVymWQ5kaxXJtTjvucJWf0j7QRHA1LzxNbLqWvyZYwjvsqvK38JYVNPDx4iTfn/UjAF6CFD/XWk4Ot4S2Sr/ew5u2XfwZr5rKwq/uBc4Ky4Maj2Q36Kj9GC6tahc48qI=
  project: ./blog/.vuepress/dist
